[package]
name = "issuers"
version = "0.12.0-beta.5"
edition = "2021"
publish = false

[[bin]]
name = "nia"
path = "src/nia.rs"

[[bin]]
name = "cfa"
path = "src/cfa.rs"

[[bin]]
name = "uda"
path = "src/uda.rs"

[lib]

[dependencies]
amplify = "~4.8.0"
strict_types = "~2.8.2"
zk-aluvm = { version = "0.12.0-beta.5", features = ["std"] }
hypersonic = { version = "0.12.0-beta.5", features = ["std"] }
rgb-interfaces = "0.12.0-beta.5"

[dev-dependencies]
zk-aluvm = { version = "0.12.0-beta.5", features = ["std", "log"] }

[features]
default = ["std"]
all = ["std"]
std = [] # must-use feature

[patch.crates-io]
aluvm = { git = "https://github.com/AluVM/aluvm", branch = "master" }
zk-aluvm = { git = "https://github.com/AluVM/zk-aluvm", branch = "master" }
ultrasonic = { git = "https://github.com/AluVM/ultrasonic", branch = "master" }
hypersonic = { git = "https://github.com/AluVM/sonic", branch = "master" }
sonic-api = { git = "https://github.com/AluVM/sonic", branch = "master" }
rgb-interfaces = { git = "https://github.com/RGB-WG/rgb-interfaces", branch = "v0.12" }
