[package]
name = "issuers"
version = "0.12.0-rc.1"
edition = "2021"
publish = false

[[bin]]
name = "fna"
path = "src/bin/rgb20/fna.rs"

[[bin]]
name = "uda"
path = "src/bin/rgb21/uda.rs"

[[bin]]
name = "uac"
path = "src/bin/rgb21/uac.rs"

[[bin]]
name = "fac"
path = "src/bin/rgb21/fac.rs"

[[bin]]
name = "dua"
path = "src/bin/rgb25/dua.rs"

[lib]

[dependencies]
amplify = "~4.9.0"
strict_types = "~2.9.0"
zk-aluvm = { version = "0.12.0-rc.1", features = ["std"] }
hypersonic = { version = "0.12.0-rc.1", features = ["std"] }
rgb-interfaces = "0.12.0-rc.1"

[dev-dependencies]
zk-aluvm = { version = "0.12.0-rc.1", features = ["std", "log"] }

[features]
default = ["std"]
all = ["std"]
std = [] # must-use feature
